<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;

class InvoiceNo extends Model
{
    use HasUuids;

    // this is a table that keeps the settings for the invoice number
    // and also the latest invoice number used. 
    // the invoice number is generated by the prefix, length and suffix.
    // there is only one record in this table.

    protected $table = 'invoice_nos';
    protected $primaryKey = 'invoice_no_id';
    protected $keyType = 'string';
    public $incrementing = false;
    protected $fillable = [
        'prefix',
        'invoice_no',
        'suffix',
        'length'
    ];

    public function getRouteKeyName(): string
    {
        return 'invoice_no_id';
    }
}
